# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_auto_20160516_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_BlogPost',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('blog.blogpost',),
        ),
    ]
